stages:
  - build
  - test
  - deploy

build-job-db:
  image: docker:dind
  stage: build
  variables:
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/clinic/healthierclinic-app/db:latest -f db/Dockerfile db/
    - docker push $CI_REGISTRY/clinic/healthierclinic-app/db:latest

build-job-nginx:
  image: docker:dind
  stage: build
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/clinic/healthierclinic-app/nginx:latest -f nginx/Dockerfile nginx/
    - docker push $CI_REGISTRY/clinic/healthierclinic-app/nginx:latest

build-job-php:
  image: docker:dind
  stage: build
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/clinic/healthierclinic-app/php:latest -f php/Dockerfile php/
    - docker push $CI_REGISTRY/clinic/healthierclinic-app/php:latest

test-job-db:
  image: docker:dind
  stage: test
  script:
    - docker container rm -f db nginx
    - docker compose up -d --build --force-recreate db
    - sleep 10
    - echo "Testando conexão"
    - docker exec db bash -c "netstat -tuln | grep 3306"

test-job-nginx:
  image: $CI_REGISTRY/clinic/healthierclinic-app/nginx:latest
  stage: test
  script:
    - nginx -t  # Verifica se a configuração do Nginx está correta
    - nginx
    - ps aux | grep nginx
    - apk add --no-cache curl
    - curl -I http://localhost || exit 1  # Testa se o servidor responde corretamente


test-job-php:
  image: $CI_REGISTRY/clinic/healthierclinic-app/php:latest
  stage: test
  script:
    - cat /etc/os-release
    - cd /var/www/html
    - php -l $(ls *.php)

deploy:
  image: docker:dind
  stage: deploy
  script:
    - docker container rm -f web db phpfpm
    - docker compose up -d --build