services:
  db:
    container_name: db
    build: ./db
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - "db/.env"
    networks:
      mysharednet:
        ipv4_address: 172.19.0.2
  web:
    container_name: web
    build: ./nginx
    ports:
      - 80:80
    networks:
      mysharednet:
        ipv4_address: 172.19.0.3
  phpfpm:
    container_name: phpfpm
    build: ./php
    networks:
      mysharednet:
        ipv4_address: 172.19.0.4

volumes:
  mysqldata:

networks:
      mysharednet:
        external: true
